periodics:

# Verify the latest-ci-updown-green version of kops, against most of the e2e tests
# Publishes gs://kops-ci/bin/latest-ci-green.txt
- interval: 1h
  name: e2e-kops-aws-k8s-latest
  labels:
    preset-service-account: "true"
    preset-aws-ssh: "true"
    preset-aws-credential: "true"
    preset-e2e-platform-aws: "true"
  decorate: true
  decoration_config:
    timeout: 90m
  spec:
    containers:
    - command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      args:
      - --cluster=e2e-kops-aws-k8s-latest.test-cncf-aws.k8s.io
      - --deployment=kops
      - --kops-ssh-user=ubuntu
      - --env=KUBE_SSH_USER=ubuntu
      - --env=KOPS_ARCH=amd64
      - --env=KOPS_DEPLOY_LATEST_URL=https://storage.googleapis.com/kubernetes-release-dev/ci/latest.txt
      - --env=KOPS_RUN_TOO_NEW_VERSION=1
      - --extract=ci/latest
      - --ginkgo-parallel
      - --kops-args=--container-runtime=containerd --networking=calico
      - --kops-priority-path=/workspace/kubernetes/platforms/linux/amd64
      - --kops-publish=gs://kops-ci/bin/latest-ci-green.txt
      - --kops-version=https://storage.googleapis.com/kops-ci/bin/latest-ci-updown-green.txt
      - --provider=aws
      - --test_args=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[HPA\]|Dashboard|RuntimeClass|RuntimeHandler
      - --timeout=60m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20210309-0688fde-master
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-kops, google-aws, kops-versions
    testgrid-days-of-results: "30"
    testgrid-tab-name: kops-aws-k8s-latest

- interval: 3h
  name: e2e-kops-aws-k8s-1-20
  labels:
    preset-service-account: "true"
    preset-aws-ssh: "true"
    preset-aws-credential: "true"
  decorate: true
  decoration_config:
    timeout: 90m
  spec:
    containers:
    - command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      args:
      - --cluster=e2e-kops-aws-k8s-1-20.test-cncf-aws.k8s.io
      - --deployment=kops
      - --kops-ssh-user=ubuntu
      - --env=KUBE_SSH_USER=ubuntu
      - --env=KOPS_DEPLOY_LATEST_URL=https://storage.googleapis.com/kubernetes-release/release/latest-1.20.txt
      - --env=KOPS_KUBE_RELEASE_URL=https://storage.googleapis.com/kubernetes-release/release
      - --env=KOPS_RUN_TOO_NEW_VERSION=1
      - --extract=release/latest-1.20
      - --ginkgo-parallel
      - --kops-args=--container-runtime=containerd --networking=calico
      - --kops-priority-path=/workspace/kubernetes/platforms/linux/amd64
      - --kops-version=https://storage.googleapis.com/kops-ci/bin/latest-ci-updown-green.txt
      - --provider=aws
      - --test_args=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[HPA\]|Dashboard|RuntimeClass|RuntimeHandler
      - --timeout=60m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20210309-0688fde-master
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-kops, google-aws, kops-versions
    testgrid-days-of-results: "30"
    testgrid-tab-name: kops-aws-k8s-1.20

- interval: 3h
  name: e2e-kops-aws-k8s-1-19
  labels:
    preset-service-account: "true"
    preset-aws-ssh: "true"
    preset-aws-credential: "true"
  decorate: true
  decoration_config:
    timeout: 90m
  spec:
    containers:
    - command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      args:
      - --cluster=e2e-kops-aws-k8s-1-19.test-cncf-aws.k8s.io
      - --deployment=kops
      - --kops-ssh-user=ubuntu
      - --env=KUBE_SSH_USER=ubuntu
      - --env=KOPS_DEPLOY_LATEST_URL=https://storage.googleapis.com/kubernetes-release/release/latest-1.19.txt
      - --env=KOPS_KUBE_RELEASE_URL=https://storage.googleapis.com/kubernetes-release/release
      - --extract=release/latest-1.19
      - --ginkgo-parallel
      - --kops-args=--container-runtime=containerd --networking=calico
      - --kops-priority-path=/workspace/kubernetes/platforms/linux/amd64
      - --kops-version=https://storage.googleapis.com/kops-ci/bin/latest-ci-updown-green.txt
      - --provider=aws
      - --test_args=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[HPA\]|Dashboard|RuntimeClass|RuntimeHandler
      - --timeout=60m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20210309-0688fde-master
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-kops, google-aws, kops-versions
    testgrid-days-of-results: "30"
    testgrid-tab-name: kops-aws-k8s-1.19

- interval: 8h
  name: e2e-kops-aws-k8s-1-18
  labels:
    preset-service-account: "true"
    preset-aws-ssh: "true"
    preset-aws-credential: "true"
  decorate: true
  decoration_config:
    timeout: 90m
  spec:
    containers:
    - command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      args:
      - --cluster=e2e-kops-aws-k8s-1-18.test-cncf-aws.k8s.io
      - --deployment=kops
      - --kops-ssh-user=ubuntu
      - --env=KUBE_SSH_USER=ubuntu
      - --env=KOPS_DEPLOY_LATEST_URL=https://storage.googleapis.com/kubernetes-release/release/stable-1.18.txt
      - --env=KOPS_KUBE_RELEASE_URL=https://storage.googleapis.com/kubernetes-release/release
      - --extract=release/stable-1.18
      - --ginkgo-parallel
      - --kops-args=--container-runtime=containerd --networking=calico
      - --kops-priority-path=/workspace/kubernetes/platforms/linux/amd64
      - --kops-version=https://storage.googleapis.com/kops-ci/bin/latest-ci-updown-green.txt
      - --provider=aws
      - --test_args=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[HPA\]|Dashboard|RuntimeClass|RuntimeHandler
      - --timeout=60m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20210309-0688fde-master
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-kops, google-aws, kops-versions
    testgrid-days-of-results: "30"
    testgrid-tab-name: kops-aws-k8s-1.18

- interval: 12h
  name: e2e-kops-aws-k8s-1-17
  labels:
    preset-service-account: "true"
    preset-aws-ssh: "true"
    preset-aws-credential: "true"
  decorate: true
  decoration_config:
    timeout: 90m
  spec:
    containers:
    - command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      args:
      - --cluster=e2e-kops-aws-k8s-1-17.test-cncf-aws.k8s.io
      - --deployment=kops
      - --kops-ssh-user=admin
      - --env=KUBE_SSH_USER=admin
      - --env=KOPS_DEPLOY_LATEST_URL=https://storage.googleapis.com/kubernetes-release/release/stable-1.17.txt
      - --env=KOPS_KUBE_RELEASE_URL=https://storage.googleapis.com/kubernetes-release/release
      - --extract=release/stable-1.17
      - --ginkgo-parallel
      - --kops-args=--container-runtime=containerd --networking=calico
      - --kops-priority-path=/workspace/kubernetes/platforms/linux/amd64
      - --kops-version=https://storage.googleapis.com/kops-ci/bin/latest-ci-updown-green.txt
      - --provider=aws
      - --test_args=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[HPA\]|Dashboard|RuntimeClass|RuntimeHandler
      - --timeout=60m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20210309-0688fde-master
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-kops, google-aws, kops-versions
    testgrid-days-of-results: "30"
    testgrid-tab-name: kops-aws-k8s-1.17

- interval: 12h
  name: e2e-kops-aws-k8s-1-16
  labels:
    preset-service-account: "true"
    preset-aws-ssh: "true"
    preset-aws-credential: "true"
  decorate: true
  decoration_config:
    timeout: 90m
  spec:
    containers:
    - command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      args:
      - --cluster=e2e-kops-aws-k8s-1-16.test-cncf-aws.k8s.io
      - --deployment=kops
      - --kops-ssh-user=admin
      - --env=KUBE_SSH_USER=admin
      - --env=KOPS_DEPLOY_LATEST_URL=https://storage.googleapis.com/kubernetes-release/release/stable-1.16.txt
      - --env=KOPS_KUBE_RELEASE_URL=https://storage.googleapis.com/kubernetes-release/release
      - --extract=release/stable-1.16
      - --ginkgo-parallel
      - --kops-args=--container-runtime=containerd --networking=calico
      - --kops-image=379101102735/debian-stretch-hvm-x86_64-gp2-2020-07-20-58035
      - --kops-priority-path=/workspace/kubernetes/platforms/linux/amd64
      - --kops-version=https://storage.googleapis.com/kops-ci/bin/latest-ci-updown-green.txt
      - --provider=aws
      - --test_args=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[HPA\]|Dashboard|RuntimeClass|RuntimeHandler
      - --timeout=60m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20210309-0688fde-master
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-kops, google-aws, kops-versions
    testgrid-days-of-results: "30"
    testgrid-tab-name: kops-aws-k8s-1.16

- interval: 12h
  name: e2e-kops-aws-k8s-1-15
  labels:
    preset-service-account: "true"
    preset-aws-ssh: "true"
    preset-aws-credential: "true"
  decorate: true
  decoration_config:
    timeout: 90m
  spec:
    containers:
    - command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      args:
      - --cluster=e2e-kops-aws-k8s-1-15.test-cncf-aws.k8s.io
      - --deployment=kops
      - --kops-ssh-user=admin
      - --env=KUBE_SSH_USER=admin
      - --env=KOPS_DEPLOY_LATEST_URL=https://storage.googleapis.com/kubernetes-release/release/stable-1.15.txt
      - --env=KOPS_KUBE_RELEASE_URL=https://storage.googleapis.com/kubernetes-release/release
      - --extract=release/stable-1.15
      - --ginkgo-parallel
      - --kops-image=379101102735/debian-stretch-hvm-x86_64-gp2-2020-07-20-58035
      - --kops-priority-path=/workspace/kubernetes/platforms/linux/amd64
      - --kops-version=https://storage.googleapis.com/kops-ci/bin/latest-ci-updown-green.txt
      - --provider=aws
      - --test_args=--ginkgo.focus=\[Conformance\]|\[NodeConformance\] --ginkgo.skip=\[Slow\]|\[Serial\]|AdmissionWebhook|Aggregator|CustomResource
      - --timeout=60m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20210309-0688fde-master
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-kops, google-aws, kops-versions
    testgrid-days-of-results: "30"
    testgrid-tab-name: kops-aws-k8s-1.15
