periodics:
# Verify the latest master branch of kops, with some of the simpler e2e tests
# Publishes gs://kops-ci/bin/latest-ci-updown-green.txt
- interval: 60m
  name: e2e-kops-aws-misc-updown
  labels:
    preset-service-account: "true"
    preset-aws-ssh: "true"
    preset-aws-credential: "true"
  decorate: true
  decoration_config:
    timeout: 45m
  spec:
    containers:
    - command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      args:
      - --cluster=e2e-kops-aws-updown.test-cncf-aws.k8s.io
      - --deployment=kops
      - --kops-ssh-user=ubuntu
      - --env=KUBE_SSH_USER=ubuntu
      - --env=KOPS_DEPLOY_LATEST_URL=https://storage.googleapis.com/kubernetes-release/release/stable.txt
      - --env=KOPS_KUBE_RELEASE_URL=https://storage.googleapis.com/kubernetes-release/release
      - --env=KOPS_RUN_TOO_NEW_VERSION=1
      - --extract=release/stable
      - --ginkgo-parallel
      - --kops-args=--networking=calico
      - --kops-publish=gs://kops-ci/bin/latest-ci-updown-green.txt
      - --kops-version=https://storage.googleapis.com/kops-ci/bin/latest-ci.txt
      - --provider=aws
      - --test_args=--ginkgo.focus=\[k8s.io\]\sNetworking.*\[Conformance\]
      - --timeout=45m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20210309-0688fde-master
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-kops, google-aws, kops-misc
    testgrid-tab-name: kops-aws-updown

- interval: 30m
  name: ci-kops-build
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
  spec:
    containers:
    - image: gcr.io/k8s-testimages/kubekins-e2e:v20210309-0688fde-experimental
      args:
      - --repo=k8s.io/kops
      - --repo=k8s.io/release
      - --root=/go/src
      - --timeout=30
      - --scenario=execute
      - --
      - make
      - gcs-publish-ci
      - GCS_LOCATION=gs://kops-ci/bin
      # docker-in-docker needs privileged mode
      securityContext:
        privileged: true
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-kops, kops-presubmits
    testgrid-tab-name: kops-build
    testgrid-alert-email: release-team@kubernetes.io
- interval: 4h
  name: e2e-kops-aws-misc-upgrade
  always_run: false
  labels:
    preset-service-account: "true"
    preset-aws-ssh: "true"
    preset-aws-credential: "true"
    preset-bazel-scratch-dir: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-dind-enabled: "true"
    preset-e2e-platform-aws: "true"
  decorate: true
  decoration_config:
    timeout: 2h
  extra_refs:
  - org: kubernetes
    repo: kops
    base_ref: master
    workdir: true
    path_alias: k8s.io/kops
  spec:
    containers:
    - image: gcr.io/k8s-testimages/kubekins-e2e:latest-experimental
      imagePullPolicy: Always
      command:
      - runner.sh
      args:
      - ./tests/e2e/scenarios/upgrade/run-test
      env:
      - name: CLOUD_PROVIDER
        value: aws
      - name: CLUSTER_NAME
        value: e2e-f9b0e6b3f9-bb3c3.test-cncf-aws.k8s.io
      - name: KOPS_STATE_STORE
        value: s3://k8s-kops-prow
      securityContext:
        privileged: true
      resources:
        requests:
          memory: "6Gi"
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-kops, google-aws, kops-misc, kops-kubetest2
    testgrid-days-of-results: "30"
    testgrid-tab-name: kops-aws-upgrade
