presubmits:
  bazelbuild/rules_k8s:
  - name: pull-rules-k8s-e2e
    cluster: gke_rules-k8s_us-central1-f_testing
    always_run: true
    decorate: true
    spec:
      containers:
      - image: gcr.io/rules-k8s/gcloud-bazel:v20200619-v0.4-44-g992f469
        args:
        - bash
        - -c
        - |
          gcloud auth activate-service-account --key-file=/etc/gcp/service-account.json \
          && gcloud container clusters get-credentials testing --zone=us-central1-f --project=rules-k8s \
          && echo "startup --host_jvm_args=-Duser.name=prow" > /root/.bazelrc \
          && ./test-e2e.sh
        env:
        - name: USER
          value: prow
        volumeMounts:
        - name: service-account
          mountPath: /etc/gcp
      volumes:
      - name: service-account
        secret:
          secretName: service-account
    annotations:
      testgrid-dashboards: google-rules_k8s
