periodics:
- name: ci-build-and-push-k8s-at-golang-tip
  interval: 4h
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
  annotations:
    testgrid-alert-email: kubernetes-sig-scale@googlegroups.com, kubernetes-scalability-tickets@google.com, go-kubernetes-scalability-tickets@googlegroups.com
    testgrid-dashboards: sig-scalability-golang
    testgrid-num-failures-to-alert: "3"
    testgrid-tab-name: build-and-push-k8s-at-golang-tip
  spec:
    containers:
      - image: gcr.io/k8s-testimages/bootstrap:v20210226-def39e5
        args:
        - --root=/go/src
        - --repo=k8s.io/perf-tests=master
        - --timeout=75
        - --scenario=execute
        - --
        - make
        - --
        - --directory=/go/src/k8s.io/perf-tests/golang
        - K8S_COMMIT=e97c570a4ba5ba1e2285d3278396937feaa15385 # head of release-1.18 branch as of 2020-04-28
        - K8S_RELEASE_COMMIT=5ad08a0987f35d7b7280e847078987f58c6f8e1f # head of master branch as of 2020-05-04
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 4
            memory: "16Gi"
          limits:
            cpu: 4
            memory: "16Gi"

- interval: 4h
  name: ci-golang-tip-k8s-1-18
  cluster: scalability
  tags:
  - "perfDashPrefix: golang-tip-k8s-1-18"
  - "perfDashBuildsCount: 240"
  - "perfDashJobType: performance"
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
    preset-dind-enabled: "true"
    preset-e2e-kubemark-common: "true"
    preset-e2e-kubemark-gce-scale: "true"
    preset-e2e-scalability-periodics: "true"
    preset-e2e-scalability-periodics-master: "true"
  annotations:
    testgrid-alert-email: kubernetes-sig-scale@googlegroups.com, kubernetes-scalability-tickets@google.com, go-kubernetes-scalability-tickets@googlegroups.com
    testgrid-dashboards: sig-scalability-golang
    testgrid-num-failures-to-alert: "3"
    testgrid-tab-name: golang-tip-k8s-1-18
  spec:
    containers:
    - args:
      - --timeout=210
      # head of perf-tests' master as of 2020-11-06
      - --repo=k8s.io/perf-tests=master:39a6c09ddca620a430d38e5de1400844ea954c2f
      - --root=/go/src
      - --scenario=kubernetes_e2e
      - --
      - --cluster=gce-golang
      - --env=CL2_ENABLE_PVS=false
      - --env=CL2_LOAD_TEST_THROUGHPUT=50
      - --env=KUBEMARK_CONTROLLER_MANAGER_TEST_ARGS=--profiling --kube-api-qps=200 --kube-api-burst=200
      - --env=KUBEMARK_SCHEDULER_TEST_ARGS=--profiling --kube-api-qps=200 --kube-api-burst=200
      - --extract=gs://k8s-scale-golang-build/ci/latest-1.18.txt
      - --gcp-node-size=e2-standard-8
      - --gcp-nodes=50
      - --gcp-project=k8s-presubmit-scale
      - --gcp-zone=us-east1-b
      - --provider=gce
      - --kubemark
      - --kubemark-nodes=2500
      - --test=false
      - --test-cmd=$GOPATH/src/k8s.io/perf-tests/golang/run-e2e.sh
      - --test-cmd-args=cluster-loader2
      - --test-cmd-args=--experimental-gcp-snapshot-prometheus-disk=true
      - --test-cmd-args=--experimental-prometheus-disk-snapshot-name=${JOB_NAME}-${BUILD_ID}
      - --test-cmd-args=--nodes=2500
      - --test-cmd-args=--provider=kubemark
      - --test-cmd-args=--report-dir=/workspace/_artifacts
      - --test-cmd-args=--testconfig=testing/load/config.yaml
      - --test-cmd-args=--testoverrides=./testing/experiments/enable_restart_count_check.yaml
      - --test-cmd-args=--testoverrides=./testing/experiments/ignore_known_kubemark_container_restarts.yaml
      - --test-cmd-args=--testoverrides=./testing/overrides/5000_nodes.yaml
      - --test-cmd-args=--testoverrides=./testing/load/golang/custom_api_call_thresholds.yaml
      - --test-cmd-name=ClusterLoaderV2
      - --timeout=180m
      - --use-logexporter
      image: gcr.io/k8s-testimages/kubekins-e2e:v20210309-0688fde-master
      env:
      - name: CL2_ENABLE_VIOLATIONS_FOR_API_CALL_PROMETHEUS
        value: "true"
      # docker-in-docker needs privilged mode
      securityContext:
        privileged: true
      resources:
        requests:
          cpu: 6
          memory: "16Gi"
        limits:
          cpu: 6
          memory: "16Gi"
