dashboard_groups:
- dashboard_names:
  - kubevirt-presubmits
  - kubevirt-periodics
  name: kubevirt
dashboards:
- dashboard_tab:
  - code_search_url_template:
      url: https://github.com/kubevirt/kubevirt/compare/<start-custom-0>...<end-custom-0>
    description: 'prowjob_name: pull-kubevirt-check-tests-for-flakes'
    name: pull-kubevirt-check-tests-for-flakes
    open_bug_template:
      url: https://github.com/kubevirt/kubevirt/issues/
    test_group_name: pull-kubevirt-check-tests-for-flakes
  - code_search_url_template:
      url: https://github.com/kubevirt/kubevirt/compare/<start-custom-0>...<end-custom-0>
    description: 'prowjob_name: pull-kubevirt-e2e-k8s-1.17'
    name: pull-kubevirt-e2e-k8s-1.17
    open_bug_template:
      url: https://github.com/kubevirt/kubevirt/issues/
    test_group_name: pull-kubevirt-e2e-k8s-1.17
  - code_search_url_template:
      url: https://github.com/kubevirt/kubevirt/compare/<start-custom-0>...<end-custom-0>
    description: 'prowjob_name: pull-kubevirt-e2e-k8s-1.17-rook-ceph'
    name: pull-kubevirt-e2e-k8s-1.17-rook-ceph
    open_bug_template:
      url: https://github.com/kubevirt/kubevirt/issues/
    test_group_name: pull-kubevirt-e2e-k8s-1.17-rook-ceph
  - code_search_url_template:
      url: https://github.com/kubevirt/kubevirt/compare/<start-custom-0>...<end-custom-0>
    description: 'prowjob_name: pull-kubevirt-e2e-k8s-1.18'
    name: pull-kubevirt-e2e-k8s-1.18
    open_bug_template:
      url: https://github.com/kubevirt/kubevirt/issues/
    test_group_name: pull-kubevirt-e2e-k8s-1.18
  - code_search_url_template:
      url: https://github.com/kubevirt/kubevirt/compare/<start-custom-0>...<end-custom-0>
    description: 'prowjob_name: pull-kubevirt-e2e-k8s-1.19'
    name: pull-kubevirt-e2e-k8s-1.19
    open_bug_template:
      url: https://github.com/kubevirt/kubevirt/issues/
    test_group_name: pull-kubevirt-e2e-k8s-1.19
  - code_search_url_template:
      url: https://github.com/kubevirt/kubevirt/compare/<start-custom-0>...<end-custom-0>
    description: 'prowjob_name: pull-kubevirt-e2e-k8s-1.20'
    name: pull-kubevirt-e2e-k8s-1.20
    open_bug_template:
      url: https://github.com/kubevirt/kubevirt/issues/
    test_group_name: pull-kubevirt-e2e-k8s-1.20
  - code_search_url_template:
      url: https://github.com/kubevirt/kubevirt/compare/<start-custom-0>...<end-custom-0>
    description: 'prowjob_name: pull-kubevirt-e2e-k8s-cnao-1.19'
    name: pull-kubevirt-e2e-k8s-cnao-1.19
    open_bug_template:
      url: https://github.com/kubevirt/kubevirt/issues/
    test_group_name: pull-kubevirt-e2e-k8s-cnao-1.19
  - code_search_url_template:
      url: https://github.com/kubevirt/kubevirt/compare/<start-custom-0>...<end-custom-0>
    description: 'prowjob_name: pull-kubevirt-e2e-kind-1.17-sriov'
    name: pull-kubevirt-e2e-kind-1.17-sriov
    open_bug_template:
      url: https://github.com/kubevirt/kubevirt/issues/
    test_group_name: pull-kubevirt-e2e-kind-1.17-sriov
  - code_search_url_template:
      url: https://github.com/kubevirt/kubevirt/compare/<start-custom-0>...<end-custom-0>
    description: 'prowjob_name: pull-kubevirt-e2e-windows2016'
    name: pull-kubevirt-e2e-windows2016
    open_bug_template:
      url: https://github.com/kubevirt/kubevirt/issues/
    test_group_name: pull-kubevirt-e2e-windows2016
  - code_search_url_template:
      url: https://github.com/kubevirt/kubevirt/compare/<start-custom-0>...<end-custom-0>
    description: 'prowjob_name: pull-kubevirt-unit-test'
    name: pull-kubevirt-unit-test
    open_bug_template:
      url: https://github.com/kubevirt/kubevirt/issues/
    test_group_name: pull-kubevirt-unit-test
  name: kubevirt-presubmits
- dashboard_tab:
  - code_search_url_template:
      url: https://github.com/kubevirt/kubevirt/compare/<start-custom-0>...<end-custom-0>
    description: 'prowjob_name: periodic-kubevirt-e2e-k8s-latest'
    name: periodic-kubevirt-e2e-k8s-latest
    open_bug_template:
      url: https://github.com/kubevirt/kubevirt/issues/
    test_group_name: periodic-kubevirt-e2e-k8s-latest
  - code_search_url_template:
      url: https://github.com/kubevirt/kubevirt/compare/<start-custom-0>...<end-custom-0>
    description: 'prowjob_name: periodic-kubevirt-e2e-k8s-prev'
    name: periodic-kubevirt-e2e-k8s-prev
    open_bug_template:
      url: https://github.com/kubevirt/kubevirt/issues/
    test_group_name: periodic-kubevirt-e2e-k8s-prev
  - code_search_url_template:
      url: https://github.com/kubevirt/kubevirt/compare/<start-custom-0>...<end-custom-0>
    description: 'prowjob_name: periodic-kubevirt-e2e-k8s-prev-prev'
    name: periodic-kubevirt-e2e-k8s-prev-prev
    open_bug_template:
      url: https://github.com/kubevirt/kubevirt/issues/
    test_group_name: periodic-kubevirt-e2e-k8s-prev-prev
  - code_search_url_template:
      url: https://github.com/kubevirt/kubevirt/compare/<start-custom-0>...<end-custom-0>
    description: 'prowjob_name: periodic-kubevirt-push-nightly-conformance'
    name: periodic-kubevirt-push-nightly-conformance
    open_bug_template:
      url: https://github.com/kubevirt/kubevirt/issues/
    test_group_name: periodic-kubevirt-push-nightly-conformance
  name: kubevirt-periodics
test_groups:
- days_of_results: 60
  gcs_prefix: kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-latest
  name: periodic-kubevirt-e2e-k8s-latest
- days_of_results: 60
  gcs_prefix: kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-prev
  name: periodic-kubevirt-e2e-k8s-prev
- days_of_results: 60
  gcs_prefix: kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-prev-prev
  name: periodic-kubevirt-e2e-k8s-prev-prev
- gcs_prefix: kubevirt-prow/logs/periodic-kubevirt-push-nightly-conformance
  name: periodic-kubevirt-push-nightly-conformance
- gcs_prefix: kubevirt-prow/pr-logs/directory/pull-kubevirt-check-tests-for-flakes
  name: pull-kubevirt-check-tests-for-flakes
  num_columns_recent: 20
- gcs_prefix: kubevirt-prow/pr-logs/directory/pull-kubevirt-e2e-k8s-1.17
  name: pull-kubevirt-e2e-k8s-1.17
  num_columns_recent: 20
- gcs_prefix: kubevirt-prow/pr-logs/directory/pull-kubevirt-e2e-k8s-1.17-rook-ceph
  name: pull-kubevirt-e2e-k8s-1.17-rook-ceph
  num_columns_recent: 20
- gcs_prefix: kubevirt-prow/pr-logs/directory/pull-kubevirt-e2e-k8s-1.18
  name: pull-kubevirt-e2e-k8s-1.18
  num_columns_recent: 20
- gcs_prefix: kubevirt-prow/pr-logs/directory/pull-kubevirt-e2e-k8s-1.19
  name: pull-kubevirt-e2e-k8s-1.19
  num_columns_recent: 20
- gcs_prefix: kubevirt-prow/pr-logs/directory/pull-kubevirt-e2e-k8s-1.20
  name: pull-kubevirt-e2e-k8s-1.20
  num_columns_recent: 20
- gcs_prefix: kubevirt-prow/pr-logs/directory/pull-kubevirt-e2e-k8s-cnao-1.19
  name: pull-kubevirt-e2e-k8s-cnao-1.19
  num_columns_recent: 20
- gcs_prefix: kubevirt-prow/pr-logs/directory/pull-kubevirt-e2e-kind-1.17-sriov
  name: pull-kubevirt-e2e-kind-1.17-sriov
  num_columns_recent: 20
- gcs_prefix: kubevirt-prow/pr-logs/directory/pull-kubevirt-e2e-windows2016
  name: pull-kubevirt-e2e-windows2016
  num_columns_recent: 20
- gcs_prefix: kubevirt-prow/pr-logs/directory/pull-kubevirt-unit-test
  name: pull-kubevirt-unit-test
  num_columns_recent: 20
