presubmits:
  kubernetes-sigs/cluster-api-provider-digitalocean:
  - name: pull-cluster-api-provider-digitalocean-test
    always_run: true
    optional: false
    decorate: true
    path_alias: "sigs.k8s.io/cluster-api-provider-digitalocean"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20210309-0688fde-1.18
        command:
        - "./scripts/ci-test.sh"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-digitalocean
      testgrid-tab-name: pr-test
  - name: pull-cluster-api-provider-digitalocean-build
    always_run: true
    optional: false
    decorate: true
    path_alias: "sigs.k8s.io/cluster-api-provider-digitalocean"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20210309-0688fde-1.18
        command:
        - "./scripts/ci-build.sh"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-digitalocean
      testgrid-tab-name: pr-build
  - name: pull-cluster-api-provider-digitalocean-verify
    always_run: true
    optional: false
    decorate: true
    path_alias: "sigs.k8s.io/cluster-api-provider-digitalocean"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20210309-0688fde-1.18
        command:
        - make
        args:
        - verify
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-digitalocean
      testgrid-tab-name: pr-verify
  - name: pull-cluster-api-provider-digitalocean-lint
    always_run: true
    optional: false
    decorate: true
    path_alias: "sigs.k8s.io/cluster-api-provider-digitalocean"
    spec:
      containers:
      - image: golangci/golangci-lint:v1.21.0
        command:
        - make
        args:
        - lint
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-digitalocean
      testgrid-tab-name: pr-lint
  - name: pull-cluster-api-provider-digitalocean-e2e
    always_run: true
    optional: false
    decorate: true
    path_alias: "sigs.k8s.io/cluster-api-provider-digitalocean"
    decoration_config:
      timeout: 5h
    max_concurrency: 1
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
      preset-do-credential: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20210309-0688fde-1.18
        command:
          - "runner.sh"
          - "./scripts/ci-e2e.sh"
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 1
            memory: "4Gi"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-digitalocean
      testgrid-tab-name: pr-e2e
  - name: pull-cluster-api-provider-digitalocean-conformance-v1alpha3
    always_run: false
    optional: true
    decorate: true
    path_alias: "sigs.k8s.io/cluster-api-provider-digitalocean"
    decoration_config:
      timeout: 5h
    max_concurrency: 1
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
      preset-do-credential: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20210309-0688fde-1.18
        command:
          - "runner.sh"
          - "./scripts/ci-conformance.sh"
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 2
            memory: "9Gi"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-digitalocean
      testgrid-tab-name: pr-conformance
